// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $('.carousel').each(function() {
      return $(this).carousel({
        cycle: 5000
      });
    });
  });

}).call(this);
